[theme]
primaryColor = "#2978B5"              
backgroundColor = "#F0F4F8"           
secondaryBackgroundColor = "#E0ECF3"  
textColor = "#1C1C1E"                 
font = "sans serif"                   
